# Form implementation generated from reading ui file 'remoteGui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import QPixmap


class Ui_TvRemote(object):

    def setupUi(self, TvRemote):
        TvRemote.setObjectName("TvRemote")
        TvRemote.resize(800, 600)
        TvRemote.setMinimumSize(QtCore.QSize(800, 599))
        TvRemote.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=TvRemote)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(360, 220, 71, 61))
        self.powerButton.setObjectName("powerButton")
        self.channelUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelUp.setGeometry(QtCore.QRect(280, 280, 41, 41))
        self.channelUp.setObjectName("channelUp")
        self.channelLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.channelLabel.setGeometry(QtCore.QRect(277, 335, 60, 16))
        self.channelLabel.setObjectName("channelLabel")
        self.channelDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelDown.setGeometry(QtCore.QRect(280, 370, 41, 41))
        self.channelDown.setObjectName("channelDown")
        self.volumeUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeUp.setGeometry(QtCore.QRect(480, 280, 41, 41))
        self.volumeUp.setObjectName("volumeUp")
        self.volumeDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeDown.setGeometry(QtCore.QRect(480, 370, 41, 41))
        self.volumeDown.setObjectName("volumeDown")
        self.volumeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.volumeLabel.setGeometry(QtCore.QRect(480, 335, 60, 16))
        self.volumeLabel.setObjectName("volumeLabel")
        self.muteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(360, 420, 71, 61))
        self.muteButton.setObjectName("muteButton")
        self.muteLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.muteLabel.setGeometry(QtCore.QRect(380, 400, 31, 15))
        self.muteLabel.setText("")
        self.muteLabel.setObjectName("muteLabel")
        self.displayImage(self.muteLabel, "redLine")
        self.muteLabel.setVisible(False)
        self.channelImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.channelImage.setGeometry(QtCore.QRect(140, 10, 530, 170))
        self.channelImage.setText("")
        self.channelImage.setObjectName("channelImage")
        self.displayImage(self.channelImage, "BBC.png")
        self.channelImage.setVisible(False)
        self.channelNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.channelNumber.setGeometry(QtCore.QRect(219, 325, 31, 31))
        self.channelNumber.setText("")
        self.channelNumber.setObjectName("channelNumber")
        self.volumeNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.volumeNumber.setGeometry(QtCore.QRect(550, 325, 31, 31))
        self.volumeNumber.setText("")
        self.volumeNumber.setObjectName("volumeNumber")
        TvRemote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TvRemote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        TvRemote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=TvRemote)
        self.statusbar.setObjectName("statusbar")
        TvRemote.setStatusBar(self.statusbar)

        self.retranslateUi(TvRemote)
        QtCore.QMetaObject.connectSlotsByName(TvRemote)

    def retranslateUi(self, TvRemote):
        _translate = QtCore.QCoreApplication.translate
        TvRemote.setWindowTitle(_translate("TvRemote", "Tv Remote"))
        self.powerButton.setText(_translate("TvRemote", "Power"))
        self.channelUp.setText(_translate("TvRemote", "+"))
        self.channelLabel.setText(_translate("TvRemote", "Channel"))
        self.channelDown.setText(_translate("TvRemote", "-"))
        self.volumeUp.setText(_translate("TvRemote", "+"))
        self.volumeDown.setText(_translate("TvRemote", "-"))
        self.volumeLabel.setText(_translate("TvRemote", "Volume"))
        self.muteButton.setText(_translate("TvRemote", "Mute"))

    def displayImage(self, label, path):
        pixmap = QtGui.QPixmap(path)
        pixmap = pixmap.scaled(200, 150, aspectRatioMode=QtCore.Qt.AspectRatioMode.KeepAspectRatio)
        label.setPixmap(QtGui.QPixmap(pixmap))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TvRemote = QtWidgets.QMainWindow()
    ui = Ui_TvRemote()
    ui.setupUi(TvRemote)
    TvRemote.show()
    sys.exit(app.exec())
